version: '3.7'
services:
    proxy:
        container_name: proxy
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse:/dev/fuse
        image: ghcr.io/thaibault/proxy:latest
        security_opt:
            - apparmor:unconfined
