version: '3.7'
services:
    environment:
        PROXY_CERTIFICATES_START_UPDATE_DELAY: 0
    proxy:
        ports:
            - "4443:443"
            - "8080:80"
        volumes:
            # Used for interactive script testing.
            - ../../scripts:/application/scripts
