version: '3.7'
services:
    proxy:
        ports:
            - "4443:443"
            - "8080:80"
        volumes:
            - ../../etc/containerBase:/etc/containerBase
            - ../../etc/nginx/conf.d:/etc/nginx/conf.d
            - /srv/http:/srv/http
