version: '3.7'
services:
    proxy:
        ports:
            - "4443:443"
            - "8080:80"
        volumes:
            # Used for interactive script testing.
            - ../../scripts:/application/scripts
