version: '3'
services:
    proxy:
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../../etc/containerBase:/etc/containerBase
            - ../../etc/nginx/conf.d:/etc/nginx/conf.d
            - /srv/http:/srv/http
