version: '3'
services:
    proxy:
        build: ./
        container_name: proxy
        cap_add:
          - SYS_ADMIN
        devices:
          - /dev/fuse:/dev/fuse
        image: tsickert/proxy:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - /srv/http:/srv/http
