apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2019-10-12T18:55:07Z'
  labels:
    app: proxy
  name: proxy_pod
spec:
  containers:
  - env:
    - name: container
      value: podman
    image: docker.io/tsickert/proxy:latest
    name: proxy
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    - containerPort: 443
      hostPort: 4443
      protocol: TCP
    workingDir: /application
    volumeMounts:
    - mountPath: /etc/containerBase
      name: containerBaseConfiguration
    - mountPath: /etc/nginx/conf.d
      name: nginxConfiguration
    - mountPath: /srv/http
      name: webRoot
  volumes:
  - name: containerBaseConfiguration
    hostPath:
      path: ./etc/containerBase
      type: Directory
  - name: nginxConfiguration
    hostPath:
      path: ./etc/nginx/conf.d
      type: Directory
  - name: webRoot
    hostPath:
      path: /srv/http
      type: Directory
