apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-10-12T18:55:07Z"
  labels:
    app: proxy
  name: proxy_pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/bin/initialize
    env:
    - name: container
      value: podman
    image: docker.io/tsickert/proxy:latest
    name: proxy
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsUser: 1000
      runAsGroup: 100
    workingDir: /application/
    volumeMounts:
    - mountPath: /etc/dockerBase
      name: containerBaseConfiguration
    - mountPath: /etc/nginx/conf.d
      name: nginxConfiguration
    - mountPath: /srv/http
      name: webRoot
  volumes:
  - name: containerBaseConfiguration
    hostPath:
      path: ./etc/dockerBase
      type: Directory
  - name: nginxConfiguration
    hostPath:
      path: ./etc/nginx/conf.d
      type: Directory
  - name: webRoot
    hostPath:
      path: /srv/http
      type: Directory
status: {}
