name: Build x86-64 image and push
on:
  # NOTE: Runs on branch or tag creation.
  create:
    branches: [ master ]
  schedule:
    # Run every Sunday at 2am o'clock.
    - cron: '0 2 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: thaibault/build-image-push-action@main
        with:
          name: ${{ env.IMAGE_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
